### PR TITLE
Updated cursor

### PR DESCRIPTION
**Pull request by saykaren**
I updated the cursor to be able to let
the user know they are able to select the mole
to hit

### CODE REVIEW

**Comment by Thunderbolt2-o** [comment]
Nice work, I just want to know where did you found my repo. I hope I have followed all the hacktoberfest rules for my repo. If you feel anything was missing feel free  to ask me

**Comment by saykaren** [comment]
Hello!

Thanks for letting me contribute.

I went to explore and did #hacktoberfest and selected html.

**Comment by Thunderbolt2-o** [comment]
Please let me know if your this PR got  eligible 😀 for hacktoberfest

**Comment by saykaren** [comment]
Yes it's in the wait period now, thank you for your help :)
Karen Garcia
saykaren@gmail.com
www.sayKaren.com

**Pull request merged**
